# Generated by Django 3.2.7 on 2021-09-25 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210925_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='demo_link',
        ),
    ]
