# Generated by Django 3.2.7 on 2021-09-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='img/profiles/user-default.png', null=True, upload_to='img/users/'),
        ),
    ]
