# Generated by Django 3.2.7 on 2021-10-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_gmail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
