# Generated by Django 3.2.7 on 2021-10-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_social_gmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='social_gmail',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
    ]
