# Generated by Django 3.2.7 on 2021-10-08 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_skill_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_gmail',
        ),
    ]
